
[build]
  cmd = "make static/app.js  && CGO_ENABLED=1 go build -o ./tmp/folio ./cmd/folio"
  bin = "./tmp/folio"
  include_ext = ["go", "ts", "html"]
  include_dir = ["cmd", "internal", "src", "static"]
  exclude_dir = ["tmp", ".js"]
