[build]
  cmd = "make static/app.js static/style.css && go build -o ./tmp/folio ./cmd/folio/"
  bin = "./tmp/folio"
  args_bin = ["server"]
  include_ext = ["go", "ts", "css", "html"]
  include_dir = ["cmd", "internal", "src", "templates"]
  exclude_dir = ["tmp", ".js"]
